### ISSUE TITLE
Mods

### ISSUE THREAD

**Issue by mtr-static-official** [DokiMod/next.dokimod.cn#3]
寻找 Mod（ https://dokimod.cn/player/moddiscover.html ）请求加入 https://mods.monika.love/
精选Mod（ https://dokimod.cn/mods/ ）添加最新MAS汉化原贴链接 https://forum.monika.love/d/234-mas-monika-after-story-0119/8

**Comment by imgradeone** [comment]
Done
`next` 分支文档需要重做，故未完全修改（）（）（）
